apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk1-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk1-app
  template:
    metadata:
      labels:
        app: dwk1-app
    spec:
      containers:
        - name: dwk1
          image: PROJECT/IMAGE
          ports:
            - containerPort: 3000
