name: test

on:
  push:

jobs:
  build-publish:
    name: Build, Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: TAG
        if: github.ref_type == 'tag'
        run: echo "TAG"

      - name: NOT TAG
        if: github.ref_type != 'tag'
        run: echo "NOT TAG"

      - name: Set working directory
        id: set-dir
        run: echo "DIR=${{ github.ref_type == 'tag' && 'overlays/prod/' || 'overlays/staging/' }}" >> $GITHUB_ENV

      - name: ls
        working-directory: ${{ env.DIR }}
        run: |
          ls -a
          pwd

      - name: dibag 
        run: '${{ env.DIR }}/kustomization.yaml'
