name: test

on:
  push:

jobs:
  build-publish:
    name: Build, Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: TAG
        if: github.ref_type == 'tag'
        run: echo "TAG"

      - name: NOT TAG
        if: github.ref_type != 'tag'
        run: echo "NOT TAG"

      - name: ls
        working-directory: ${{ github.ref_type == 'tag' ? overlays/prod/ : overlays/staging/ }}
        run: ls
