name: test

on:
  push:

jobs:
  test:
    name: test shit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: mluukkai/k25_project_conf
          ref: 'main'
          token:  ${{ secrets.REPO_TOKEN }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: debug
        run: ls -la
      - name: add shit
        run: touch test.txt
      - run: git push origin main